service: alexa-spanish-proverbs

custom:
  secrets: ${file(secrets.json)}
  alexa:
    vendorId: ${self:custom.secrets.AMAZON_VENDOR_ID}
    clientId: ${self:custom.secrets.AMAZON_CLIENT_ID}
    clientSecret: ${self:custom.secrets.AMAZON_CLIENT_SECRET}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-east-1

plugins:
  - serverless-alexa-skills
