service: alexa-spanish-proverbs

custom:
  secrets: ${file(secrets.json)}
  alexa:
    vendorId: ${self:custom.secrets.AMAZON_VENDOR_ID}
    clientId: ${self:custom.secrets.AMAZON_VENDOR_ID}
    clientSecret: ${self:custom.secrets.AMAZON_VENDOR_ID}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

plugins:
  - serverless-alexa-skills
