service: alexa-spanish-proverbs

custom:
  secrets: ${file(secrets.json)}
  alexa:
    vendorId: ${self:custom.secrets.AMAZON_VENDOR_ID}
    clientId: ${self:custom.secrets.AMAZON_CLIENT_ID}
    clientSecret: ${self:custom.secrets.AMAZON_CLIENT_SECRET}
    skills:
      - id: ${self:custom.secrets.ALEXA_SKILL_ID}
        manifest:
          publishingInformation:
            locales:
              es-ES:
                name: refranes
          apis:
            custom:
              endpoint:
                uri: arn:aws:lambda:region:account-id:function:function-name
          manifestVersion: '1.0'

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-east-1

plugins:
  - serverless-alexa-skills
