service: alexa-proverbs

custom:
  secrets: ${file(secrets.json)}
  alexa:
    vendorId: ${self:custom.secrets.AMAZON_VENDOR_ID}
    clientId: ${self:custom.secrets.AMAZON_CLIENT_ID}
    clientSecret: ${self:custom.secrets.AMAZON_CLIENT_SECRET}
    skills:
      - id: ${self:custom.secrets.ALEXA_SKILL_ID}
        manifest:
          publishingInformation:
            locales:
              es-ES:
                name: refranes
          apis:
            custom:
              endpoint:
                api: ${self:custom.secrets.LAMBDA_PROVERBS}
          manifestVersion: '1.0'
        models:
          es-ES:
            interactionModel:
              languageModel:
                invocationName: 'refranero digital'
                types:
                  - name: THEME
                    values:
                      - name:
                          value: AMOR
                      - name:
                          value: VINO
                      - name:
                          value: PAN
                      - name:
                          value: NIÑOS
                      - name:
                          value: GENTE
                      - name:
                          value: MAR
                      - name:
                          value: RIOS
                intents:
                  - name: AMAZON.RepeatIntent
                  - name: AMAZON.HelpIntent
                  - name: AMAZON.StopIntent
                  - name: AMAZON.CancelIntent
                  - name: ProverbIntent
                    slots:
                    - name: Theme
                      type: THEME
                    samples:
                     - 'un refran sobre {Theme}'
                     - 'un refran relacionado con {Theme}'
                     - 'que te diga un refran'

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

functions:
  proverbs:
    handler: lambda/proverbs.tellMeAProverb
    events:
      - alexaSkill:
          appId: ${self:custom.secrets.ALEXA_SKILL_ID}

plugins:
  - serverless-alexa-skills
